http:
  port: 8080
  hostname: YOUR_LOCAL_IP
https:
  port: 8080
  hostname: localhost
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # User's routes
  user: 
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: YOUR_LOCAL_IP
    paths: ['/users/','/users/*']
  auth: 
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: YOUR_LOCAL_IP
    paths: '/auth/*'
  transaction: 
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: YOUR_LOCAL_IP
    paths: '/transactions/*'
  contact: 
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: YOUR_LOCAL_IP
    paths: ['/contacts/','/contacts/*']
serviceEndpoints:
  userService:
    url: 'http://YOUR_LOCAL_IP:3000'
  authService:
    url: 'http://YOUR_LOCAL_IP:3001'
  transactionService:
    url: 'http://YOUR_LOCAL_IP:3003'
  contactService:
    url: 'http://YOUR_LOCAL_IP:3004'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
  transactionPipeline:
    apiEndpoints:
      - transaction
    policies:
      - proxy:
          - action:
              serviceEndpoint: transactionService
              changeOrigin: true
  contactPipeline:
    apiEndpoints:
      - contact
    policies:
      - proxy:
          - action:
              serviceEndpoint: contactService
              changeOrigin: true