http:
  port: 8080
  hostname: 192.168.1.2
https:
  port: 8080
  hostname: localhost
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # User's routes
  user: 
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: 192.168.1.2
    paths: ['/users/','/users/*']
  auth: 
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: 192.168.1.2
    paths: '/auth/*'
  register: 
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: 192.168.1.2
    paths: '/register/*'
  transaction: 
    methods: 'GET,POST,PUT,PATCH,DELETE' 
    host: 192.168.1.2
    paths: '/transaction/*'
serviceEndpoints:
  userService:
    url: 'http://192.168.1.2:3000'
  authService:
    url: 'http://192.168.1.2:3001'
  registerService:
    url: 'http://192.168.1.2:3002'
  transactionService:
    url: 'http://192.168.1.2:3003'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
  registerPipeline:  
    apiEndpoints:
      - register
    policies:
      - proxy:
          - action:
              serviceEndpoint: registerService
              changeOrigin: true
  transactionPipeline:
    apiEndpoints:
      - transaction
    policies:
      - proxy:
          - action:
              serviceEndpoint: transactionService
              changeOrigin: true
