http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  # User's routes
  user: 
    methods: 'GET,POST,PUT' 
    host: localhost
    paths: ['/users/','/users/*']
  auth: 
    methods: 'GET,POST,PUT'
    host: localhost
    paths: '/auth/*'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  userService:
    url: 'http://localhost:3000'
  authService:
    url: 'http://localhost:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  userPipeline:
    apiEndpoints:
      - user
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - auth
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
