http:
  port: 8080
  hostname: 192.168.1.2
https:
  port: 8080
  hostname: localhost
admin:
  port: 9876
  host: localhost
apiEndpoints:
  # User's routes
  user: 
    methods: 'GET,POST,PUT' 
    host: 192.168.1.2
    paths: ['/users/','/users/*']
  auth: 
    methods: 'GET,POST,PUT'
    host: 192.168.1.2
    paths: '/auth/*'
serviceEndpoints:
  userService:
    url: 'http://192.168.1.2:3000'
  authService:
    url: 'http://192.168.1.2:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  userPipeline:
    apiEndpoints:
      - user
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService
              changeOrigin: true
  authPipeline:
    apiEndpoints:
      - auth
    policies:
      - proxy:
          - action:
              serviceEndpoint: authService
              changeOrigin: true
